services:
  orientamed-api:
    build:
      context: ./          # Working directory for Docker
      dockerfile: ./Dockerfile
    restart: always
    image: orientamed-api-image
    ports:
      - "7861:8000"
    volumes:
      - ./core:/app/core
      - ./data:/app/data
      - ./api_utils:/app/api_utils
      - ./api.py:/app/api.py
      - ./api_settings.yaml:/app/api_settings.yaml
      - ./favicon.ico:/app/favicon.ico
    working_dir: /app
    command: uvicorn api:app --host 0.0.0.0 --port 8000
